import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./index.css";
import "../styles/index.scss";
import StoreProvider from "@/app/StoreProvider";
import { AlertProvider } from "@/context/alertContext";
import HeaderBar from "@/components/HeaderBar";
import apis from "@/apis";
import HeaderLogged from "@/components/Header/HeaderLogged";
import GlobalData from "@/components/GlobalData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ET Wishlist",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const data = await apis.getGlobalData();  

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AlertProvider>
            <div className="bg-white font-body">
              <GlobalData data={data} />
              <HeaderBar />
              <HeaderLogged />
              {children}
            </div>
          </AlertProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
